In [1]:
# sort dict by value

xs = {'a': 4, 'b': 3, 'c': 2, 'd': 1}
sorted(xs.items(), key=lambda x: x[1])

[('d', 1), ('c', 2), ('b', 3), ('a', 4)]

In [2]:
# test multiple flags

x, y, z = 0, 1, 0
1 in (x, y, z)

True

In [4]:
# merging dicts

x = {'a': 1, 'b': 2}
y = {'b': 3, 'c': 4}
z = {**x, **y}
z
# {'a': 1, 'c': 4, 'b': 3}

{'a': 1, 'b': 3, 'c': 4}

In [5]:
my_dict = {'a': 23, 'b': 42, 'c': 0xc0ffee}

import json
print(json.dumps(my_dict, indent=4, sort_keys=True))

{
    "a": 23,
    "b": 42,
    "c": 12648430
}


In [ ]:
# convert jupyter notebook to document
#
# jupyter nbconvert -- to html my_notebook.ipynb

In [7]:
# dict as switch/case

def dispatch_dict(operator, x, y):
    return {
        'add': lambda: x + y,
        'sub': lambda: x - y,
        'mul': lambda: x * y,
        'div': lambda: x / y,
    }.get(operator, lambda: None)()

dispatch_dict('add', 3, 4)

7

In [3]:
# Connected components of array

import numpy as np
from scipy.ndimage.measurements import label

array = np.ones((3, 3))

array[1,:] = 0

labeled_array, number_of_components = label(array)

print(labeled_array, number_of_components)

[[1 1 1]
 [0 0 0]
 [2 2 2]] 2


In [5]:
# make maze

def make_maze(w=16, h=8):
    """
    Creating a random maze.
    Parameters:
        w : int
            width of maze
        h : int
            height of maze

    Returns:
        s : String of maze
    """
    import random

    vis = [[0] * w + [1] for _ in range(h)] + [[1] * (w + 1)]
    ver = [["|  "] * w + ["|"] for _ in range(h)] + [[]]
    hor = [["+--"] * w + ["+"] for _ in range(h + 1)]

    def walk(x, y):
        """
        Random walk in maze
        """
        vis[y][x] = 1

        d = [(x - 1, y), (x, y + 1), (x + 1, y), (x, y - 1)]
        random.shuffle(d)
        for (xx, yy) in d:
            if vis[yy][xx]:
                continue
            if xx == x:
                hor[max(y, yy)][x] = "+  "
            if yy == y:
                ver[y][max(x, xx)] = "   "
            walk(xx, yy)

    walk(random.randrange(w), random.randrange(h))

    s = ""
    for (a, b) in zip(hor, ver):
        s += "".join(a + ["\n"] + b + ["\n"])
    return s


maze = make_maze()
print(maze)

+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
|                 |                    |     |  |
+  +--+  +--+--+  +--+--+  +--+--+--+  +  +  +  +
|  |     |     |     |     |     |  |     |  |  |
+  +  +--+  +  +--+  +  +--+  +  +  +--+--+  +  +
|  |  |     |  |  |     |     |  |        |  |  |
+--+  +  +--+--+  +--+--+  +--+  +--+  +  +  +  +
|     |  |     |           |        |  |  |     |
+  +--+  +  +  +--+--+  +--+--+--+  +  +  +--+  +
|        |  |           |     |        |     |  |
+--+--+--+  +--+--+--+--+  +  +  +--+--+--+  +  +
|        |     |     |     |  |     |     |  |  |
+--+--+  +  +  +  +  +  +--+  +  +--+  +  +--+  +
|        |  |  |  |     |  |  |  |     |  |     |
+  +--+--+  +  +  +--+--+  +  +--+  +--+  +  +--+
|           |              |           |        |
+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+


